### ISSUE TITLE
螺旋正方形

### ISSUE THREAD

**Issue by SakigamiYang** [PyChina/funny-python#3]
## 概述
海龟作图画出正方形的螺旋堆叠。

## 前置条件（选填）
Tkinter

## 代码
```python
from turtle import Turtle

t = Turtle()


def spiral(n):
    if n < 300:
        t.forward(n)
        t.right(89)
        spiral(n + 1)


spiral(30)
input('Press any key to continue...')

```

## 说明（选填）
画完大概是这个样子。
![螺旋方形](https://user-images.githubusercontent.com/15279135/73364892-4b369100-42e6-11ea-996f-bd9de1d20ac4.png)

**Comment by Prodesire** [comment]
赞！
